name: Actualizar Notas de Lanzamiento

on:
  push:
    branches:
      - main
      - release
      - dev

jobs:
  update_release_notes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Necesario para obtener el historial completo de todas las ramas

    - name: Configurar .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' # Asegúrate de que coincida con tu versión de .NET Core

    - name: Ejecutar script para actualizar notas de lanzamiento
      id: update_script
      run: |
        # Dar permisos de ejecución al script generate_release_notes.sh
        chmod +x ./scripts/generate_release_notes.sh
        # Ejecutar el script generate_release_notes.sh
        ./scripts/generate_release_notes.sh

    - name: Comprobar si hay cambios y commitear
      id: commit
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add env-release-note.md
        # Solo commitear si hay cambios detectados para evitar commits vacíos
        git diff --quiet --exit-code || git commit -m "chore(release): Actualizar env-release-note.md [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}